sudo: false
cache: pip
language: python
python:
- '3.6'
- '3.5'
- '2.7'
- pypy
env:
- MARSHMALLOW_VERSION="==2.15.2"
- MARSHMALLOW_VERSION=""
install:
- travis_retry pip install -r dev-requirements.txt
- travis_retry pip install -U marshmallow"$MARSHMALLOW_VERSION" --pre
script: invoke test
jobs:
  include:
  - stage: PyPI Release
    if: tag IS present
    python: '3.6'
    env: []
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: sloria
      password:
        secure: AAmcCtVO+rlvpLYoMf54t48AljAWgnTQGL7rqDE9tkkbbQU36cUlFmUsRkGKJzzdMi5Ai3InoFv+WvjDzQwMH0bS+tV0PBn03N4bGfBzmChDnzwTdtNl+7IO26LLdkzANTon+cRDn8xwFGdXAzhOpODhmNEYfHVlaFsmAV2oIahwh01KxXxFFInDHXZF9ml++XByXY+k8VELyqv+JMuBrxFsReLFOFBB2HKdXOaOOJ/Qt0Ht/fv38h/QaHb5exnEx5PkzAC/pDBk2GUJ21/eCiJ91+P7U3CpqF6bqwUC6E5mosfL782IKjJob4Cjmjshgxjh7pH9HtxYpXxPDur13MibfjVrObMBEttEjd0OsB7pnq0aFBZGWWmiKi6Qd6A/l4AZZL+I1luoQXFDAVscGjpcpIeOuncCB9XhzK8EOYTeuqG1h56q1v4k4Yz8vTJucDwV5ySTb0syR0kCD5YVHHQio1L1s33NA6ASq8npgcxe9BwfRIoR+ZmMkm8d5G/ARbHwZSDytfY6p9I4gVrqTyWYWQ+QhWfbrxHzz/9rR3TU4SZJxQvyMrenlzds1KysCN75LO0jzTTf1TCE7oXXz/8o1SVSUh39Fm1zoBgnJYVRO+Zv55b1d6JXT18fWaioJ5RMIRTRvn+0Nf3/AQ78wOM/m5pp22Aaj2Hvak4KjZs=
      on:
        tags: true
      distributions: sdist bdist_wheel
